### ISSUE TITLE
Script is not a BTTask

### ISSUE THREAD

**Issue by HexBlit** [limbonaut/limboai#111]
Hey I was trying to add a new task via the add task button. But when I created it and tried to add it to the behavior tree it says its not a BTTask.

The behavior dir and task dir is defined and the files are saved in each appropriate dir. 

![Screenshot 2024-05-19 233403](https://github.com/limbonaut/limboai/assets/1005054/2f66fc13-2223-41e9-840f-6f17e0b84a4a)

![Screenshot 2024-05-19 233309](https://github.com/limbonaut/limboai/assets/1005054/18199c96-7c09-4cec-a43c-b59b7b5772fb)

```
limboai\editor\limbo_ai_editor_plugin.cpp:133 - LimboAI: Failed to instantiate task. Script is not a BTTask: res://ai/tasks/new_task.gd
limboai\editor\limbo_ai_editor_plugin.cpp:83 - Condition "p_task.is_null()" is true.
```

**Comment by HexBlit** [comment]
There must be some way to get into this state, i just deleted everything and settings and made a new behavior and BTAction and now it is happy...

**Comment by limbonaut** [comment]
Need to know how to reproduce this in order to fix it. What that error means is that script is not recognized as BTTask when asked. Could be a Godot bug.

**Comment by limbonaut** [comment]
This bug might have been fixed in v1.1.0. Not entirely sure, though, since I couldn't reproduce exactly this state.

**Comment by agroff** [comment]
I just had the same issue in 1.1.0 using godot 4.3.beta1. I just deleted the demo folder and restarted godot and now it is working. For me the issue occurred in the first task I tried to create after installing the plugin (didn't restart godot after installing). 

Hopefully this helps either reproduce or workaround the issue.

**Comment by Trece-1101** [comment]
> This bug might have been fixed in v1.1.0. Not entirely sure, though, since I couldn't reproduce exactly this state.

Hi. Still an issue on v1.1.0
It has nothing to do with "demo" scene. I installed LimboAI without that folder.
There's nothing special to do to reproduce the bug. Just create a New Task from the Tree Editor. Also, I changed the default (tree and task) folders but when trying to create the first New Task the default route still was the old "res:\\ai\tasks"
I changed the route and created the new task, It didn't have the default Icon (no icon) and gave me the "Script is not a BTTask" error.
But the fix is easy... close and restart Godot Editor and that's it. The task takes an icon by itself and works.
After that, you can work without that error (I created another New Task and didn't encounter the issue)

**Comment by stebl** [comment]
Just had this error on Godot 4.2.  Fresh LimboAI install.  The demo worked great.  Error shows up when adding custom nodes to the behavior tree. 

Godot restart worked 👍

**Comment by limbonaut** [comment]
@stebl 
Did you restart the editor after you installed the plugin? I suspect that this error happens if the plugin is installed and used without restarting the editor right after.

**Comment by stebl** [comment]
I didn't restart anything, the plugin failed.  I did a "project reload"
which is not quite a full editor restart, then I had success.

I agree I think it's an issue that only shows up on the first install.

I'm fairly new to godot, maybe it's best practice to refresh whenever
adding a new plugin?

**Comment by limbonaut** [comment]
Maybe I could find a way to ask the user to restart the editor on first install.

**Comment by smedelyan** [comment]
Try making the script `@tool`
